### PR TITLE
Makefile now installs centrifuge-kreport

### LINKED ISSUE #58: centrifuge-kreport doesn't exist
Just as the title says.

Only the following exist:
`centrifuge                         centrifuge-build-bin-debug         centrifuge-class-debug             centrifuge-inspect                 centrifuge-RemoveEmptySequence.pl
centrifuge-build                   centrifuge-BuildSharedSequence.pl  centrifuge-compress.pl             centrifuge-inspect-bin             centrifuge-RemoveN.pl
centrifuge-build-bin               centrifuge-class                   centrifuge-download                centrifuge-inspect-bin-debug       centrifuge-sort-nt.pl`

### PR DESCRIPTION
**Pull request by laserson**
Fixes #58

### CODE REVIEW

**Comment by laserson** [comment]
Sorry for all the diff noise...my editor removes trailing whitespace.  Let me know if I should fix that before you pull in this PR.

**Comment by fbreitwieser** [comment]
Hi @laserson , thanks for the contribution! Yes, please get rid of the whitespace changes to make the commit diff more concise, and I'll merge the pull request then. Thanks

**Comment by laserson** [comment]
@fbreitwieser done.

**Comment by fbreitwieser** [comment]
Thanks!

**Comment by johnomics** [comment]
centrifuge-kreport also needs to be added to the list of binaries to add to the PATH in the [manual](https://github.com/infphilo/centrifuge/blob/master/MANUAL) (lines 85-90).

**Pull request merged**
